repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
      - id: lint
        name: lint
        entry: make lint
        language: system
      - id: typecheck
        name: typecheck
        entry: make type-check
        language: system
      - id: secure
        name: secure
        entry: make secure
        language: system
      - id: docs
        name: docs
        entry: make docs
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false

